#!/bin/sh

SCRIPT_ROOT=`dirname "${0}"`
cd "${SCRIPT_ROOT}"

RESOURCES_DIR="DwarfBuilder.app/Contents/Resources"
DT_INI_DIR="Contents/MacOS/etc/memory_layouts/osx"

echo ""

echo "Creating a new Builder..."
rm -rf DwarfBuilder.app
cp -rp extras/DwarfBuilder.app .
mkdir "${RESOURCES_DIR}"

echo "Setting default values..."
## Visual settings
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" WINDOWED YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" INTRO NO
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" GRAPHICS YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" TILESET IRONHAND
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" TRUETYPE NO
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" FONT_FILE IRONHAND
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" FPS YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" IDLERS TOP
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" SHOW_FLOW_AMOUNTS YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" RESIZABLE YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" WINDOWEDX 1280
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" WINDOWEDY 600

## App Settings
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" SOUND NO
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" VOLUME 255
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" SOUNDTRACK DEFAULT
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" KEYBINDS LAPTOP
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" FPS_CAP 100
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" G_FPS_CAP 50

## Gameplay Settings
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" EMBARK_WARNING_ALWAYS YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" POPULATION_CAP 100
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" BABY_CHILD_CAP_ABS 15
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" BABY_CHILD_CAP_PER 20
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" EMBARK_RECTANGLE_WIDTH 3
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" EMBARK_RECTANGLE_HEIGHT 3
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" TEMPERATURE YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" WEATHER YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" INVADERS YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" GRAZING YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" AQUIFERS NO
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" RUST NO
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" CAVEINS YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" PAUSE_CAVEIN YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" PAUSE_DIG_DANGER YES

##Save Settings
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" COMPRESSED_SAVES YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" AUTOSAVE SEASONAL
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" PAUSE_ON_LOAD YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" AUTOSAVE_PAUSE YES
defaults write "${SCRIPT_ROOT}/${RESOURCES_DIR}/DwarfBuilder" AUTOBACKUP NO

# mv ${SCRIPT_ROOT}/DwarfBuilder.plist "${RESOURCES_DIR}/"

echo "Populating materials..."
cp -rp extras "${RESOURCES_DIR}/"
cp -p extras/menu "${RESOURCES_DIR}/"
cp -p extras/memory_layouts/* "${RESOURCES_DIR}/extras/DwarfTherapist.app/${DT_INI_DIR}/"

echo "Adding tilesets..."
cp -rp ironhand "${RESOURCES_DIR}/"
cp -rp jolly "${RESOURCES_DIR}/"
cp -rp mayday "${RESOURCES_DIR}/"
cp -rp phoebus "${RESOURCES_DIR}/"

echo "Reticulating splines..."
cp -rp vanilla "${RESOURCES_DIR}/"
cp -rp soundsense "${RESOURCES_DIR}/"

echo "Cleaning up..."
rm -rf "${RESOURCES_DIR}/extras/DwarfBuilder.app"
rm -rf "${RESOURCES_DIR}/extras/menu"
rm -rf "${RESOURCES_DIR}/extras/memory_layouts"

echo ""
echo "Finished! Don't forget to follow the checklist:"
echo ""
echo "1) Update instructions."
echo "   convert to PDF"
echo "2) Update tilesets, apps, mods."
echo "   Dwarf Fortress"
echo "   Dwarf Therapist"
echo "   Sound Sense"
echo "   Phoebus"
echo "   Ironhand"
echo "   Jolly Bastion"
echo "   Mayday"
echo "3) Check icons."
echo "   dwarfort.exe"
echo "   DwarfFortress.app"
echo "   DwarfBuilder.app"
echo "   DwarfTherapist.app"
echo "   SoundSense.app"
echo "4) Clean up .DS_Store."
echo "   find . -iname '.ds_store' -delete."
echo "5) Zip up the app and the PDF."
echo "6) Update forum."
echo "   markup file"
echo "   forum post"
echo "   forum title"
echo "7) Upload to plaidsoft, dffd, github."
