#!/bin/sh

SCRIPT_ROOT=`dirname "${0}"`
cd "${SCRIPT_ROOT}"

RESOURCES_DIR="DwarfBuilder.app/Contents/Resources"

echo ""

echo "Populating materials..."
cp -rp extras "${RESOURCES_DIR}/"

echo "Adding tilesets..."
cp -rp ironhand "${RESOURCES_DIR}/"
cp -rp jolly "${RESOURCES_DIR}/"
cp -rp mayday "${RESOURCES_DIR}/"
cp -rp phoebus "${RESOURCES_DIR}/"

echo "Reticulating splines..."
cp -rp vanilla "${RESOURCES_DIR}/"

sed -e "s///;" \
    -i".bak" soundsense/soundSense.sh
rm soundsense/soundSense.sh.bak
chmod 755 soundsense/soundSense.sh
cp -rp soundsense "${RESOURCES_DIR}/"

echo "Cleaning up..."
rm -rf "${RESOURCES_DIR}/extras/DwarfBuilder.app"
rm -rf "${RESOURCES_DIR}/extras/menu"
rm -rf "${RESOURCES_DIR}/extras/memory_layouts"

echo ""
echo "Finished! Don't forget to follow the checklist:"
echo ""
echo "1) Update instructions."
echo "   convert to PDF"
echo "2) Update tilesets, apps, mods."
echo "   Dwarf Fortress"
echo "   Dwarf Therapist"
echo "   Sound Sense"
echo "   Phoebus"
echo "   Ironhand"
echo "   Jolly Bastion"
echo "   Mayday"
echo "3) Clean up .DS_Store."
echo "   find . -iname '.ds_store' -delete."
echo "4) Zip up the app and the PDF."
echo "5) Update forum."
echo "   markup file"
echo "   forum post"
echo "   forum title"
echo "6) Upload to plaidsoft, dffd, github."
