#!/bin/sh

RESOURCES_DIR=`dirname "${0}"`
cd "${RESOURCES_DIR}"

DB_BACKUP_DIR="../../../DwarfBuilder_backup"

DF_BUILT_APP="../../../DwarfFortress.app"
DF_SAVE_DIR="Contents/Resources/data/save"
DF_RAW_DIR="Contents/Resources/raw"

DT_BUILT_APP="../../../DwarfTherapist.app"
DT_INI_DIR="Contents/MacOS/etc/memory_layouts/osx"
DT_INI_FILE="v0.34.07.ini"

MENU="main_menu"

## Visual settings
WINDOWED=`defaults read "${RESOURCES_DIR}/DwarfBuilder" WINDOWED`
INTRO=`defaults read "${RESOURCES_DIR}/DwarfBuilder" INTRO`
GRAPHICS=`defaults read "${RESOURCES_DIR}/DwarfBuilder" GRAPHICS`
TILESET=`defaults read "${RESOURCES_DIR}/DwarfBuilder" TILESET`
TRUETYPE=`defaults read "${RESOURCES_DIR}/DwarfBuilder" TRUETYPE`
FONT_FILE=`defaults read "${RESOURCES_DIR}/DwarfBuilder" FONT_FILE`
FPS=`defaults read "${RESOURCES_DIR}/DwarfBuilder" FPS`
IDLERS=`defaults read "${RESOURCES_DIR}/DwarfBuilder" IDLERS`
SHOW_FLOW_AMOUNTS=`defaults read "${RESOURCES_DIR}/DwarfBuilder" SHOW_FLOW_AMOUNTS`
RESIZABLE=`defaults read "${RESOURCES_DIR}/DwarfBuilder" RESIZABLE`
WINDOWEDX=`defaults read "${RESOURCES_DIR}/DwarfBuilder" WINDOWEDX`
WINDOWEDY=`defaults read "${RESOURCES_DIR}/DwarfBuilder" WINDOWEDY`

## App Settings
SOUND=`defaults read "${RESOURCES_DIR}/DwarfBuilder" SOUND`
VOLUME=`defaults read "${RESOURCES_DIR}/DwarfBuilder" VOLUME`
SOUNDTRACK=`defaults read "${RESOURCES_DIR}/DwarfBuilder" SOUNDTRACK`
KEYBINDS=`defaults read "${RESOURCES_DIR}/DwarfBuilder" KEYBINDS`
FPS_CAP=`defaults read "${RESOURCES_DIR}/DwarfBuilder" FPS_CAP`
G_FPS_CAP=`defaults read "${RESOURCES_DIR}/DwarfBuilder" G_FPS_CAP`

## Gameplay Settings
EMBARK_WARNING_ALWAYS=`defaults read "${RESOURCES_DIR}/DwarfBuilder" EMBARK_WARNING_ALWAYS`
POPULATION_CAP=`defaults read "${RESOURCES_DIR}/DwarfBuilder" POPULATION_CAP`
BABY_CHILD_CAP_ABS=`defaults read "${RESOURCES_DIR}/DwarfBuilder" BABY_CHILD_CAP_ABS`
BABY_CHILD_CAP_PER=`defaults read "${RESOURCES_DIR}/DwarfBuilder" BABY_CHILD_CAP_PER`
EMBARK_RECTANGLE_WIDTH=`defaults read "${RESOURCES_DIR}/DwarfBuilder" EMBARK_RECTANGLE_WIDTH`
EMBARK_RECTANGLE_HEIGHT=`defaults read "${RESOURCES_DIR}/DwarfBuilder" EMBARK_RECTANGLE_HEIGHT`
TEMPERATURE=`defaults read "${RESOURCES_DIR}/DwarfBuilder" TEMPERATURE`
WEATHER=`defaults read "${RESOURCES_DIR}/DwarfBuilder" WEATHER`
INVADERS=`defaults read "${RESOURCES_DIR}/DwarfBuilder" INVADERS`
GRAZING=`defaults read "${RESOURCES_DIR}/DwarfBuilder" GRAZING`
AQUIFERS=`defaults read "${RESOURCES_DIR}/DwarfBuilder" AQUIFERS`
RUST=`defaults read "${RESOURCES_DIR}/DwarfBuilder" RUST`
CAVEINS=`defaults read "${RESOURCES_DIR}/DwarfBuilder" CAVEINS`

##Save Settings
COMPRESSED_SAVES=`defaults read "${RESOURCES_DIR}/DwarfBuilder" COMPRESSED_SAVES`
AUTOSAVE=`defaults read "${RESOURCES_DIR}/DwarfBuilder" AUTOSAVE`
PAUSE_ON_LOAD=`defaults read "${RESOURCES_DIR}/DwarfBuilder" PAUSE_ON_LOAD`
AUTOSAVE_PAUSE=`defaults read "${RESOURCES_DIR}/DwarfBuilder" AUTOSAVE_PAUSE`
AUTOBACKUP=`defaults read "${RESOURCES_DIR}/DwarfBuilder" AUTOBACKUP`

if [ ! -d vanilla ]
then
    echo "vanilla package required"
    exit
fi

about() {
    echo ""
    echo "About Dwarf Builder:"
    echo ""
    echo "DB will allow you to customize and \"roll your own\" Dwarf Fortress app."
    echo "No need to deal with copying folders or editing init files. Easy Peasy!"
    echo ""
    echo "On each menu screen, you'll see options with a number or letter."
    echo "Press the number or letter to go into the sub-menu or edit the option."
    echo "Some options will switch yes/no or other predefined values, and some will"
    echo "  prompt you for a new value or sometimes two values."
    echo "When you're comfortable with the settings, press 'm' to go back to the"
    echo "  main menu then press 'c' to construct your personalized Dwarf Fortress app!"
    echo ""
    echo "More information about each option can be found in the included readme."
    echo ""
    echo "Press any key to continue..."

    read -s -n1
    tput clear

    echo ""
    echo "Versions:"
    echo ""
    echo "Dwarf Builder:... v5"
    echo ""
    echo "Dwarf Fortress:.. 0.34.07"
    echo "Dwarf Therapist:. 0.6.12b4"
    echo ""
    echo "Phoebus:......... v00"
    echo "Ironhand:........ 0.68"
    echo "Jolly Bastion:... v3"
    echo "Masterwork:...... 1.7.1"
    echo "Mayday:.......... 07a"
    echo ""
    echo "Press any key to continue..."

    read -s -n1
    tput clear

    echo ""
    echo "Credits:"
    echo ""
    echo "Tilesets:"
    echo "  Phoebus (Phoebus)"
    echo "  Ironhand (Ironhand)"
    echo "  AlexanderOcias (Jolly Bastion)"
    echo "  Mike Mayday (Mayday)"
    echo "  Meph (Masterwork Font)"
    echo "Icons:"
    echo "  Linkdragon (DF icon)"
    echo "  <unknown> (DB icon)"
    echo "Embark Profiles: Phoebus, Mayday, Cap'n Duck, & LNP"
    echo "Dwarf Therapist: DwarfEngineer"
    echo "Extended Soundtrack: Meph, Solifuge, Yakoff Oskanoff"
    echo ""
    echo "And of course TOADY for this crazy game!"
    echo ""
    echo "Press any key to continue..."

    read -s -n1
    MENU="main_menu"
}

main_menu() {
    echo ""
    echo "Choose a Category:"
    echo ""
    echo "1) Visual Settings"
    echo "2) Application Settings"
    echo "3) Gameplay Settings"
    echo "4) Save Settings"
    echo ""
    echo "c) Contstruct Dwarf Fortress"
    echo "t) Install/Update Dwarf Therapist"
    echo "u) Dwarf Builder Utilities"
    echo ""
    echo "q) Save and Quit Dwarf Builder"
    echo "w) Quit Without Saving"
    echo ""
    echo "a) About & Version & Credits"
    echo ""
    echo "Choice -> \c"

    read -s -n1 CHOICE

    case ${CHOICE} in
        1)    MENU="visual_one";;
        2)    MENU="application_one";;
        3)    MENU="gameplay_one";;
        4)    MENU="save_one";;
        u|U)  MENU="dbutils_one";;
        a|A)  MENU="about";;
        c|C)  MENU="construct";;
        t|T)  MENU="therapist";;
        q|Q)  MENU="save_exit";;
        w|W)  MENU="exit_screen";;
        *)    ;;
    esac
}

visual_one() {
    echo ""
    echo "Visual Settings"
    echo ""
    echo "1) Window Mode:....... ${WINDOWED}"
    echo "2) Show Intro:........ ${INTRO}"
    echo "3) Which Tileset:..... ${TILESET}"
    echo "4) Creature Graphics:. ${GRAPHICS}"
    echo "5) Use Font:.......... ${TRUETYPE}"
    echo "6) Which Font:........ ${FONT_FILE}"
    echo "7) Show FPS:.......... ${FPS}"
    echo "8) Show Idlers:....... ${IDLERS}"
    echo "9) Liquid Depth:...... ${SHOW_FLOW_AMOUNTS}"
    echo "0) Window Size:....... ${WINDOWEDX}x${WINDOWEDY}"
    echo ""
    echo "m) Back to Main Menu"
    echo ""
    echo "Choice -> \c"

    read -s -n1 CHOICE

    case ${CHOICE} in
        1)    WINDOWED=`toggle_yn ${WINDOWED}`;;
        2)    INTRO=`toggle_yn ${INTRO}`;;
        3)    TILESET=`toggle_tileset ${TILESET}`;;
        4)    GRAPHICS=`toggle_yn ${GRAPHICS}`;;
        5)    TRUETYPE=`toggle_yn ${TRUETYPE}`;;
        6)    FONT_FILE=`toggle_fontfile ${FONT_FILE}`;;
        7)    FPS=`toggle_yn ${FPS}`;;
        8)    IDLERS=`toggle_idlers ${IDLERS}`;;
        9)    SHOW_FLOW_AMOUNTS=`toggle_yn ${SHOW_FLOW_AMOUNTS}`;;
        0)    echo ""; echo ""; echo "Window Size X: \c"
              WINDOWEDX=`input_int ${WINDOWEDX}`
              echo "Window Size Y: \c"
              WINDOWEDY=`input_int ${WINDOWEDY}`;;
        m|M)  MENU="main_menu";;
        *)    ;;
    esac
}

application_one() {
    echo ""
    echo "Application Settings"
    echo ""
    echo "1) Sound:......... ${SOUND}"
    echo "2) Volume:........ ${VOLUME}"
    echo "3) Soundtrack:.... ${SOUNDTRACK}"
    echo "4) Keybindings:... ${KEYBINDS}"
    echo "5) FPS Cap:....... ${FPS_CAP}"
    echo "6) Graphical Cap:. ${G_FPS_CAP}"
    echo ""
    echo "m) Back to Main Menu"
    echo ""
    echo "Choice -> \c"

    read -s -n1 CHOICE

    case ${CHOICE} in
        1)    SOUND=`toggle_yn ${SOUND}`;;
        2)    echo ""; echo ""; echo "Volume (0-255): \c"
              VOLUME=`input_int ${VOLUME}`;;
        3)    SOUNDTRACK=`toggle_soundtrack ${SOUNDTRACK}`;;
        4)    KEYBINDS=`toggle_keybinds ${KEYBINDS}`;;
        5)    echo ""; echo ""; echo "Processing FPS Cap (try 50-200): \c"
              FPS_CAP=`input_int ${FPS_CAP}`;;
        6)    echo ""; echo ""; echo "Graphical FPS Cap (try 30-90): \c"
              G_FPS_CAP=`input_int ${G_FPS_CAP}`;;
        m|M)  MENU="main_menu";;
        *)    ;;
    esac
}

gameplay_one() {
    echo ""
    echo "Gameplay Settings (page 1)"
    echo ""
    echo "1) Embark Warning:. ${EMBARK_WARNING_ALWAYS}"
    echo "2) Population Cap:. ${POPULATION_CAP}"
    echo "3) Baby/Child Cap:. ${BABY_CHILD_CAP_ABS}:${BABY_CHILD_CAP_PER}"
    echo "4) Embark Size:.... ${EMBARK_RECTANGLE_WIDTH}:${EMBARK_RECTANGLE_HEIGHT}"
    echo "5) Temperature:.... ${TEMPERATURE}"
    echo "6) Weather:........ ${WEATHER}"
    echo ""
    echo "n) Next Page"
    echo "m) Back to Main Menu"
    echo ""
    echo "Choice -> \c"

    read -s -n1 CHOICE

    case ${CHOICE} in
        1)    EMBARK_WARNING_ALWAYS=`toggle_yn ${EMBARK_WARNING_ALWAYS}`;;
        2)    echo ""; echo ""; echo "Population Cap: (try 50-200): \c"
              POPULATION_CAP=`input_int ${POPULATION_CAP}`;;
        3)    echo ""; echo ""; echo "Absolute Baby/Child Cap (try 0-20): \c"
              BABY_CHILD_CAP_ABS=`input_int ${BABY_CHILD_CAP_ABS}`
              echo "Percentage (of adults) Cap (try 0-50): \c"
              BABY_CHILD_CAP_PER=`input_int ${BABY_CHILD_CAP_PER}`;;
        4)    echo ""; echo ""; echo "Embark Rectangle Width (try 2-5): \c"
              EMBARK_RECTANGLE_WIDTH=`input_int ${EMBARK_RECTANGLE_WIDTH}`
              echo "Embark Rectangle Height (try 2-5): \c"
              EMBARK_RECTANGLE_HEIGHT=`input_int ${EMBARK_RECTANGLE_HEIGHT}`;;
        5)    TEMPERATURE=`toggle_yn ${TEMPERATURE}`;;
        6)    WEATHER=`toggle_yn ${WEATHER}`;;
        n|N)  MENU="gameplay_two";;
        m|M)  MENU="main_menu";;
        *)    ;;
    esac
}

gameplay_two() {
    echo ""
    echo "Gameplay Settings (page 2)"
    echo ""
    echo "1) Invaders:........ ${INVADERS}"
    echo "2) Grazing Animals:. ${GRAZING}"
    echo "3) Aquifers:........ ${AQUIFERS}"
    echo "4) Skill Rusting:... ${RUST}"
    echo "5) Cave-Ins:........ ${CAVEINS}"
    echo ""
    echo "p) Previous Page"
    echo "m) Back to Main Menu"
    echo ""
    echo "Choice -> \c"

    read -s -n1 CHOICE

    case ${CHOICE} in
        1)    INVADERS=`toggle_yn ${INVADERS}`;;
        2)    GRAZING=`toggle_yn ${GRAZING}`;;
        3)    AQUIFERS=`toggle_yn ${AQUIFERS}`;;
        4)    RUST=`toggle_yn ${RUST}`;;
        5)    CAVEINS=`toggle_yn ${CAVEINS}`;;
        p|P)  MENU="gameplay_one";;
        m|M)  MENU="main_menu";;
        *)    ;;
    esac
}

save_one() {
    echo ""
    echo "Save Settings"
    echo ""
    echo "1) Compress Saves:.... ${COMPRESSED_SAVES}"
    echo "2) Autosave:.......... ${AUTOSAVE}"
    echo "3) Pause On Load:..... ${PAUSE_ON_LOAD}"
    echo "4) Pause On Save:..... ${AUTOSAVE_PAUSE}"
    echo "5) Auto-Backup Saves:. ${AUTOBACKUP}"
    echo ""
    echo "m) Back to Main Menu"
    echo ""
    echo "Choice -> \c"

    read -s -n1 CHOICE

    case ${CHOICE} in
        1)    COMPRESSED_SAVES=`toggle_yn ${COMPRESSED_SAVES}`;;
        2)    AUTOSAVE=`toggle_autosave ${AUTOSAVE}`;;
        3)    PAUSE_ON_LOAD=`toggle_yn ${PAUSE_ON_LOAD}`;;
        4)    AUTOSAVE_PAUSE=`toggle_yn ${AUTOSAVE_PAUSE}`;;
        5)    AUTOBACKUP=`toggle_yn ${AUTOBACKUP}`;;
        m|M)  MENU="main_menu";;
        *)    ;;
    esac
}

dbutils_one() {
    echo ""
    echo "Dwarf Builder Utilities"
    echo ""
    echo "1) Backup DB Files"
    echo "2) Restore DB Files"
    echo ""
    echo "3) Update Save Raws"
    echo "4) Backup DF Saves"
    echo "5) Restore DF Saves"
    echo ""
    echo "m) Back to Main Menu"
    echo ""
    echo "Choice -> \c"

    read -s -n1 CHOICE

    case ${CHOICE} in
        1)    MENU="db_backup";;
        2)    MENU="db_restore";;
        3)    MENU="dfsave_update";;
        4)    MENU="dfsave_backup";;
        5)    MENU="dfsave_restore";;
        m|M)  MENU="main_menu";;
        *)    ;;
    esac
}

save_exit() {
    echo ""
    echo "Saving settings..."

    ## Visual settings
    defaults write "${RESOURCES_DIR}/DwarfBuilder" WINDOWED ${WINDOWED}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" INTRO ${INTRO}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" GRAPHICS ${GRAPHICS}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" TILESET ${TILESET}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" TRUETYPE ${TRUETYPE}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" FONT_FILE ${FONT_FILE}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" FPS ${FPS}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" IDLERS ${IDLERS}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" SHOW_FLOW_AMOUNTS ${SHOW_FLOW_AMOUNTS}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" RESIZABLE ${RESIZABLE}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" WINDOWEDX ${WINDOWEDX}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" WINDOWEDY ${WINDOWEDY}

    ## App Settings
    defaults write "${RESOURCES_DIR}/DwarfBuilder" SOUND ${SOUND}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" VOLUME ${VOLUME}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" SOUNDTRACK ${SOUNDTRACK}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" KEYBINDS ${KEYBINDS}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" FPS_CAP ${FPS_CAP}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" G_FPS_CAP ${G_FPS_CAP}

    ## Gameplay Settings
    defaults write "${RESOURCES_DIR}/DwarfBuilder" EMBARK_WARNING_ALWAYS ${EMBARK_WARNING_ALWAYS}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" POPULATION_CAP ${POPULATION_CAP}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" BABY_CHILD_CAP_ABS ${BABY_CHILD_CAP_ABS}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" BABY_CHILD_CAP_PER ${BABY_CHILD_CAP_PER}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" EMBARK_RECTANGLE_WIDTH ${EMBARK_RECTANGLE_WIDTH}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" EMBARK_RECTANGLE_HEIGHT ${EMBARK_RECTANGLE_HEIGHT}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" TEMPERATURE ${TEMPERATURE}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" WEATHER ${WEATHER}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" INVADERS ${INVADERS}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" GRAZING ${GRAZING}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" AQUIFERS ${AQUIFERS}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" RUST ${RUST}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" CAVEINS ${CAVEINS}

    ##Save Settings
    defaults write "${RESOURCES_DIR}/DwarfBuilder" COMPRESSED_SAVES ${COMPRESSED_SAVES}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" AUTOSAVE ${AUTOSAVE}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" PAUSE_ON_LOAD ${PAUSE_ON_LOAD}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" AUTOSAVE_PAUSE ${AUTOSAVE_PAUSE}
    defaults write "${RESOURCES_DIR}/DwarfBuilder" AUTOBACKUP ${AUTOBACKUP}

    exit_screen
}

db_backup() {
    echo ""
    echo "Backing up Dwarf Builder files..."

    rm -rf "${DB_BACKUP_DIR}"
    mkdir "${DB_BACKUP_DIR}"
    cp -p DwarfBuilder.plist "${DB_BACKUP_DIR}/"

    if [ -d dfsave_backup ]
    then
        cp -rp dfsave_backup "${DB_BACKUP_DIR}/"
    fi

    echo "Finished..."
    echo ""
    echo "Press any key to continue..."

    read -s -n1
    MENU="main_menu"
}

db_restore() {
    echo ""

    if [ -d "${DB_BACKUP_DIR}" ]
    then
        echo "Restoring Dwarf Builder files..."

        cp -p "${DB_BACKUP_DIR}/DwarfBuilder.plist" .
        cp -rp "${DB_BACKUP_DIR}/dfsave_backup" .
        rm -rf "${DB_BACKUP_DIR}"

        echo "Finished..."
        echo "Please restart the app to reload settings."
        exit
    else
        echo "Save not found..."
    fi

    echo ""
    echo "Press any key to continue..."

    read -s -n1
    MENU="main_menu"
}

dfsave_backup() {
    echo ""

    if [ -d "${DF_BUILT_APP}/${DF_SAVE_DIR}" ]
    then
        echo "Backing up game..."

        rm -rf dfsave_backup
        cp -rp "${DF_BUILT_APP}/${DF_SAVE_DIR}" dfsave_backup

        echo "Finished..."
    else
        echo "Save not found..."
    fi

    echo ""
    echo "Press any key to continue..."

    read -s -n1
    MENU="main_menu"
}

dfsave_restore() {
    echo ""

    if [ -d dfsave_backup ]
    then
        echo "Restoring Game..."

        rm -rf "${DF_BUILT_APP}/${DF_SAVE_DIR}"
        cp -rp dfsave_backup "${DF_BUILT_APP}/${DF_SAVE_DIR}"

        echo "Finished..."
    else
        echo "Save not found..."
    fi

    echo ""
    echo "Press any key to continue..."

    read -s -n1
    MENU="main_menu"
}

dfsave_update() {
    echo ""

    if [ -d "${DF_BUILT_APP}/${DF_SAVE_DIR}" ]
    then
        echo "Updating Save Raws..."

        for REGION in `ls "${DF_BUILT_APP}/${DF_SAVE_DIR}"`
        do
            if [ -d "${DF_BUILT_APP}/${DF_SAVE_DIR}/${REGION}/raw" ]
            then
                rm -rf "${DF_BUILT_APP}/${DF_SAVE_DIR}/${REGION}/raw"
                cp -rp "${DF_BUILT_APP}/${DF_RAW_DIR}" "${DF_BUILT_APP}/${DF_SAVE_DIR}/${REGION}/"
            fi
        done

        echo "Finished..."
    else
        echo "Save not found..."
    fi

    echo ""
    echo "Press any key to continue..."

    read -s -n1
    MENU="main_menu"
}

therapist() {
    echo ""

    if [ -d "${DT_BUILT_APP}/${DT_INI_DIR}" ]
    then
        echo "Updating Dwarf Therapist..."
        cp -rp "extras/DwarfTherapist.app/${DT_INI_DIR}/${DT_INI_FILE}" "${DT_BUILT_APP}/${DT_INI_DIR}/${DT_INI_FILE}"
    else
        echo "Installing Dwarf Therapist..."
        cp -rp extras/DwarfTherapist.app "${DT_BUILT_APP}"
    fi

    echo "Finished..."
    echo ""
    echo "Press any key to continue..."

    read -s -n1
    MENU="main_menu"
}

construct() {
    echo ""
    echo "Setting up Vanilla...."

    cp -rp vanilla build
    rm -rf build/raw/graphics/example/
    rm build/raw/graphics/graphics_example.txt

    case ${TILESET} in
        "PHOEBUS")
            echo "Installing Phoebus..."

            cp -rp phoebus/data/art/* build/data/art/
            cp -rp phoebus/data/init/phoebus/* build/data/init/
            cp -rp phoebus/raw/* build/raw/
            ;;

        "JOLLY_TALL")
            echo "Installing Jolly Bastion 9x12..."

            cp -rp jolly/9x12\ \(recommended\)/data/* build/data/
            cp -rp jolly/9x12\ \(recommended\)/raw/* build/raw/
            ;;

        "JOLLY_SQUARE")
            echo "Installing Jolly Bastion 12x12..."

            cp -rp jolly/12x12/data/* build/data/
            cp -rp jolly/12x12/raw/* build/raw/
            ;;

        "IRONHAND")
            echo "Installing Ironhand..."

            cp -rp ironhand/data/* build/data/
            cp -rp ironhand/raw/* build/raw/
            ;;

        "MAYDAY")
            echo "Installing Mayday..."

            cp -rp mayday/data/* build/data/
            cp -rp mayday/raw/* build/raw/
            ;;

        *)
            ;;
    esac

    echo "Tweaking init files..."

    #make it so dwarf fortress runs in a separate thread
    sed -e "s/dwarfort.exe/dwarfort.exe\& > stdout.txt 2> stderr.txt/g;" \
        -i".bak" build/df
    rm build/df.bak

    sed -e "s/\[AUTOSAVE:.*\]/\[AUTOSAVE:${AUTOSAVE}\]/g;
        s/\[PAUSE_ON_LOAD:.*\]/\[PAUSE_ON_LOAD:${PAUSE_ON_LOAD}\]/g;
        s/\[AUTOSAVE_PAUSE:.*\]/\[AUTOSAVE_PAUSE:${AUTOSAVE_PAUSE}\]/g;
        s/\[AUTOBACKUP:.*\]/\[AUTOBACKUP:${AUTOBACKUP}\]/g;
        s/\[EMBARK_WARNING_ALWAYS:.*\]/\[EMBARK_WARNING_ALWAYS:${EMBARK_WARNING_ALWAYS}\]/g;
        s/\[SHOW_FLOW_AMOUNTS:.*\]/\[SHOW_FLOW_AMOUNTS:${SHOW_FLOW_AMOUNTS}\]/g;
        s/\[IDLERS:.*\]/\[IDLERS:${IDLERS}\]/g;
        s/\[TEMPERATURE:.*\]/\[TEMPERATURE:${TEMPERATURE}\]/g;
        s/\[CAVEINS:.*\]/\[CAVEINS:${CAVEINS}\]/g;
        s/\[INVADERS:.*\]/\[INVADERS:${INVADERS}\]/g;
        s/\[WEATHER:.*\]/\[WEATHER:${WEATHER}\]/g;
        s/\[POPULATION_CAP:.*\]/\[POPULATION_CAP:${POPULATION_CAP}\]/g;
        s/\[BABY_CHILD_CAP:.*\]/\[BABY_CHILD_CAP:${BABY_CHILD_CAP_ABS}:${BABY_CHILD_CAP_PER}\]/g;
        s/\[EMBARK_RECTANGLE:.*\]/\[EMBARK_RECTANGLE:${EMBARK_RECTANGLE_WIDTH}:${EMBARK_RECTANGLE_HEIGHT}\]/g;" \
        -i".bak" build/data/init/d_init.txt
    rm build/data/init/d_init.txt.bak

    sed -e "s/\[INTRO:.*\]/\[INTRO:${INTRO}\]/g;
        s/\[WINDOWED:.*\]/\[WINDOWED:${WINDOWED}\]/g;
        s/\[SOUND:.*\]/\[SOUND:${SOUND}\]/g;
        s/\[VOLUME:.*\]/\[VOLUME:${VOLUME}\]/g;
        s/\[RESIZABLE:.*\]/\[RESIZABLE:${RESIZABLE}\]/g;
        s/\[WINDOWEDX:.*\]/\[WINDOWEDX:${WINDOWEDX}\]/g;
        s/\[WINDOWEDY:.*\]/\[WINDOWEDY:${WINDOWEDY}\]/g;
        s/\[GRAPHICS_WINDOWEDX:.*\]/\[GRAPHICS_WINDOWEDX:${WINDOWEDX}\]/g;
        s/\[GRAPHICS_WINDOWEDY:.*\]/\[GRAPHICS_WINDOWEDY:${WINDOWEDY}\]/g;
        s/\[GRAPHICS:.*\]/\[GRAPHICS:${GRAPHICS}\]/g;
        s/\[TRUETYPE:.*\]/\[TRUETYPE:${TRUETYPE}\]/g;
        s/\[FPS:.*\]/\[FPS:${FPS}\]/g;
        s/\[FPS_CAP:.*\]/\[FPS_CAP:${FPS_CAP}\]/g;
        s/\[G_FPS_CAP:.*\]/\[G_FPS_CAP:${G_FPS_CAP}\]/g;
        s/\[COMPRESSED_SAVES:.*\]/\[COMPRESSED_SAVES:${COMPRESSED_SAVES}\]/g;" \
        -i".bak" build/data/init/init.txt
    rm build/data/init/init.txt.bak

    if [ ${TILESET} == "DEFAULT_SQUARE" ]
    then
        sed -e "s/\[FONT:.*\]/\[FONT:curses_square_16x16.png\]/g;
            s/\[FULLFONT:.*\]/\[FULLFONT:curses_square_16x16.png\]/g; \
            s/\[GRAPHICS_FONT:.*\]/\[GRAPHICS_FONT:curses_square_16x16.png\]/g; \
            s/\[GRAPHICS_FULLFONT:.*\]/\[GRAPHICS_FULLFONT:curses_square_16x16.png\]/g;" \
            -i".bak" build/data/init/init.txt
        rm build/data/init/init.txt.bak
    fi

    if [ ${TILESET} == "DEFAULT_TALL" ]
    then
        sed -e "s/\[FONT:.*\]/\[FONT:curses_800x600.png\]/g;
            s/\[FULLFONT:.*\]/\[FULLFONT:curses_800x600.png\]/g; \
            s/\[GRAPHICS_FONT:.*\]/\[GRAPHICS_FONT:curses_800x600.png\]/g; \
            s/\[GRAPHICS_FULLFONT:.*\]/\[GRAPHICS_FULLFONT:curses_800x600.png\]/g;" \
            -i".bak" build/data/init/init.txt
        rm build/data/init/init.txt.bak
    fi

    if [ ${AQUIFERS} == "NO" ]
    then
        echo "Removing Aquifers..."
        sed -e "s/\[AQUIFER\]/(AQUIFER)/g;" \
            -i".bak" build/raw/objects/*.txt
        rm build/raw/objects/*.txt.bak
    fi

    if [ ${GRAZING} == "NO" ]
    then
        echo "Disabling Grazing..."
        sed -e "s/\[GRAZER:\(.*\)\]/(GRAZER:\1)/g;" \
            -i".bak" build/raw/objects/*.txt
        rm build/raw/objects/*.txt.bak
    fi
    
    if [ ${KEYBINDS} == "LAPTOP" ]
    then
        echo "Changing Keybindings..."
        sed -e "/\[BIND:SECONDSCROLL_UP:REPEAT_SLOW\]/ {n;s/\[KEY:.*\]/\[KEY:\-\]/g;};
            /\[BIND:SECONDSCROLL_DOWN:REPEAT_SLOW\]/ {n;s/\[KEY:.*\]/\[KEY:=\]/g;};
            /\[BIND:SECONDSCROLL_PAGEUP:REPEAT_SLOW\]/ {n;s/\[KEY:.*\]/\[KEY:_\]/g;};
            /\[BIND:SECONDSCROLL_PAGEDOWN:REPEAT_SLOW\]/ {n;s/\[KEY:.*\]/\[KEY:+\]/g;};
            /\[BIND:D_MILITARY_SUPPLIES_WATER_DOWN:REPEAT_NOT\]/ {n;s/\[KEY:.*\]/\[KEY:-\]/g;};
            /\[BIND:D_MILITARY_SUPPLIES_WATER_UP:REPEAT_NOT\]/ {n;s/\[KEY:.*\]/\[KEY:=\]/g;};
            /\[BIND:D_MILITARY_SUPPLIES_FOOD_DOWN:REPEAT_NOT\]/ {n;s/\[KEY:.*\]/\[KEY:_\]/g;};
            /\[BIND:D_MILITARY_SUPPLIES_FOOD_UP:REPEAT_NOT\]/ {n;s/\[KEY:.*\]/\[KEY:+\]/g;};
            /\[BIND:D_MILITARY_AMMUNITION_LOWER_AMOUNT:REPEAT_NOT\]/ {n;s/\[KEY:.*\]/\[KEY:-\]/g;};
            /\[BIND:D_MILITARY_AMMUNITION_RAISE_AMOUNT:REPEAT_NOT\]/ {n;s/\[KEY:.*\]/\[KEY:=\]/g;};
            /\[BIND:D_MILITARY_AMMUNITION_LOWER_AMOUNT_LOTS:REPEAT_NOT\]/ {n;s/\[KEY:.*\]/\[KEY:_\]/g;};
            /\[BIND:D_MILITARY_AMMUNITION_RAISE_AMOUNT_LOTS:REPEAT_NOT\]/ {n;s/\[KEY:.*\]/\[KEY:+\]/g;};" \
            -i".bak" build/data/init/interface.txt
        rm build/data/init/interface.txt.bak
    fi

    if [ ${RUST} == "NO" ]
    then
        echo "Disabling Skill Rust..."
        sed -n "1,/CREATURE:DWARF/ p" \
            build/raw/objects/creature_standard.txt > build/raw/objects/creature_standard_one.txt
        sed -n "/CREATURE:DWARF/,\$ {/CREATURE:DWARF/n;p;}" \
            build/raw/objects/creature_standard.txt > build/raw/objects/creature_standard_two.txt

        rm build/raw/objects/creature_standard.txt

        cat build/raw/objects/creature_standard_one.txt >> build/raw/objects/creature_standard.txt
        cat extras/rust_proof.txt >> build/raw/objects/creature_standard.txt
        cat build/raw/objects/creature_standard_two.txt >> build/raw/objects/creature_standard.txt

        rm build/raw/objects/creature_standard_one.txt
        rm build/raw/objects/creature_standard_two.txt
    fi


    if [ ${SOUNDTRACK} == "EXTENDED" ]
    then
        echo "Installing Extended Soundtrack..."
        cp extras/extended.ogg build/data/sound/song_game.ogg
    fi

    case ${FONT_FILE} in
        "PHOEBUS")
            echo "Installing Phoebus Font..."
            cp extras/phoebus.ttf build/data/art/font.ttf;;
        "IRONHAND")
            echo "Installing Ironhand Font..."
            cp extras/ironhand.ttf build/data/art/font.ttf;;
        "MASTERWORK")
            echo "Installing Masterwork Font..."
            cp extras/masterwork.ttf build/data/art/font.ttf;;
        "TUFFY")
            echo "Installing Tuffy Font..."
            cp extras/tuffy.ttf build/data/art/font.ttf;;
        "DEFAULT") 
            cp extras/default.ttf build/data/art/font.ttf;;
    esac

    echo "Reticulating splines..."
    cp extras/embark_profiles.txt build/data/init/

    echo "Cleaning up..."

    if [ -d "${DF_BUILT_APP}" ]
    then
        if [ -d "${DF_BUILT_APP}/${DF_SAVE_DIR}" ]
        then
            mv "${DF_BUILT_APP}/${DF_SAVE_DIR}" dfcompile_backup
        fi

        rm -rf "${DF_BUILT_APP}"
    fi

    cp -rp extras/DwarfFortress.app "${DF_BUILT_APP}"
    mv build "${DF_BUILT_APP}/Contents/Resources"

    if [ -d dfcompile_backup ]
    then
        mv dfcompile_backup "${DF_BUILT_APP}/${DF_SAVE_DIR}"
        rm -rf dfcompile_backup
    fi

    echo ""
    echo "Press any key to continue..."

    read -s -n1
    MENU="main_menu"
}

exit_screen() {
    echo ""
    echo "Thanks for choosing Dwarf Builder!"
    echo ""
    echo "You may close this terminal window now."
    echo ""

    exit
}

input_int() {
    read INPUT
    if [ ${INPUT} -eq ${INPUT} ]
    then
        echo ${INPUT}
    else
        echo ${1}
    fi
}

toggle_yn() {
    case ${1} in
        "YES") echo "NO";;
        *) echo "YES";;
    esac
}

toggle_tileset() {
    case ${1} in
        "DEFAULT_TALL") echo "IRONHAND";;
        "IRONHAND") echo "PHOEBUS";;
        "PHOEBUS") echo "JOLLY_SQUARE";;
        "JOLLY_SQUARE") echo "JOLLY_TALL";;
        "JOLLY_TALL") echo "MAYDAY";;
        "MAYDAY") echo "DEFAULT_SQUARE";;
        *) echo "DEFAULT_TALL";;
    esac
}

toggle_autosave() {
    case ${1} in
        "NONE") echo "SEASONAL";;
        "SEASONAL") echo "YEARLY";;
        *) echo "NONE";;
    esac
}

toggle_keybinds() {
    case ${1} in
        "DEFAULT") echo "LAPTOP";;
        *) echo "DEFAULT";;
    esac
}

toggle_soundtrack() {
    case ${1} in
        "DEFAULT") echo "EXTENDED";;
        *) echo "DEFAULT";;
    esac
}

toggle_fontfile() {
    case ${1} in
        "DEFAULT") echo "IRONHAND";;
        "IRONHAND") echo "PHOEBUS";;
        "PHOEBUS") echo "MASTERWORK";;
        "MASTERWORK") echo "TUFFY";;
        *) echo "DEFAULT";;
    esac
}

toggle_idlers() {
    case ${1} in
        "OFF") echo "TOP";;
        "TOP") echo "BOTTOM";;
        *) echo "OFF";;
    esac
}

while true
do
    tput clear
    ${MENU}
done
